#添加的是Eureka Server 相关的配置
server:
  port: 8761   #当前Eureka Server的服务端口
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心的访问地址
    register-with-eureka: false #是否将当前的Eureka Server服务作为客户端进行注册
    fetch-registry: false  #是否获取其他Eureka Server的服务数据


