server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CatcherOne/aispringcloud.git
          searchPaths: config
          username: Huimin Chen
          password: 123456chmA
          label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/